---
# This playbook will install mysql and create db user and give permissions.

- name: Install Mysql package (debian)
  apt: name={{ item }} state=installed
  with_items:
   - mysql-server
   - python-mysqldb
   - libselinux1
   - libsemanage1
   - iptables-persistent
  when: ansible_os_family == 'Debian'

- name: Install Mysql package (redhat)
  yum: name={{ item }} state=installed
  with_items:
   - mysql-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python
  when: ansible_os_family == 'Redhat'

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: sestatus.rc != 0

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service (debian)
  service: name=mysql state=started enabled=yes
  when: ansible_os_family == 'Debian'

- name: Start Mysql Service (redhat)
  service: name=mysqld state=started enabled=yes
  when: ansible_os_family == 'Redhat'

- name: insert iptables rule (redhat)
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
              insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
  notify: restart iptables
  when: ansible_os_family == 'Redhat'

- name: insert iptables rule (debian)
  lineinfile: dest=/etc/iptables/rules.v4 state=present regexp="{{ mysql_port }}"
              insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
  notify: reload netfilter-permanent
  when: ansible_os_family == 'Debian'

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
